### ISSUE TITLE
Мягкий ховер эффект

### ISSUE THREAD

**Issue by shmidtelson** [shmidtelson/wp-post-rating#37]
```css
.wpr-wrapp .icon-star:hover {
    transition: scale 300ms;
    scale: 1.2;
}
```
